# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Install SDMetrics to repo
      run: mvn install:install-file -Dfile="lib/SDMetricsOpenCore-2.35-mod.jar" -DgroupId="com.SDMetrics" -DartifactId="open-core" -Dversion="2.35-mod" -Dpackaging="jar"
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload TestResults Artifact
      uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: codeGenerator
        # A file, directory or wildcard pattern that describes what to upload
        path: target/CodeGenerator-1.0.jar
